# This is a basic workflow to help you get started with Actions
name: Readme Update
# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Update README
        run: npm start
      - name: Commit README
        run: |
          echo "git pull"
          git pull
          echo "git add"
          git add .
          git config --local user.email "kgh2120@gmail.com"
          git config --local user.name "kgh2120"
          echo "git commit"
          git commit -m "Update README.md" || echo "변경된 내용이 없습니다."
          echo "git push"
          git push